@php
    $isRtl = session('locale') === 'ar';
@endphp

<div class="space-y-6">
    <!-- Success Banner when redirected from Live Demo Booking -->
    @if($highlight)
        <div class="p-4 rounded-2xl bg-gradient-to-r from-emerald-900 via-teal-900 to-slate-900 text-white border border-emerald-500/50 shadow-xl flex items-center justify-between animate-pulse">
            <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-xl bg-emerald-500 text-slate-950 flex items-center justify-center font-extrabold text-xl shadow-lg">
                    ✓
                </div>
                <div>
                    <h3 class="text-sm font-extrabold text-emerald-300">
                        {{ $isRtl ? 'تم حجز الموعد تلقائياً بواسطة ReplyDesk AI!' : 'Appointment Auto-Booked by ReplyDesk AI!' }}
                    </h3>
                    <p class="text-xs text-slate-200">
                        {{ $isRtl ? 'تم إضافة موعد العميل (قص شعر @ 6:00 مساءً مع أحمد حسن) مباشرة إلى جدولك.' : 'The customer appointment (Haircut @ 6:00 PM with Ahmed Hassan) has been logged into your calendar.' }}
                    </p>
                </div>
            </div>
            <a href="{{ route('demo') }}" class="text-xs font-bold bg-slate-800 hover:bg-slate-700 px-3 py-1.5 rounded-xl border border-slate-700 text-purple-300">
                {{ $isRtl ? 'العودة للمحاكي' : 'Back to Simulator' }}
            </a>
        </div>
    @endif

    <!-- Top Greeting & Action Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
            <div class="flex items-center gap-2">
                <h1 class="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
                    {{ $isRtl ? 'مساء الخير، أحمد 👋' : 'Good afternoon, Ahmed 👋' }}
                </h1>
                <span class="px-2.5 py-1 rounded-full text-[10px] font-extrabold bg-purple-100 text-purple-800 border border-purple-200">
                    {{ $isRtl ? 'عرض توضيحي للمبيعات' : 'Sales Demo View' }}
                </span>
            </div>
            <p class="text-xs sm:text-sm text-slate-500 mt-1">
                {{ $isRtl ? 'إليك القيمة التجارية المحققة لصالون النخبة باربر دبي عبر الذكاء الاصطناعي.' : 'Real-time business performance for Elite Barber Dubai powered by ReplyDesk AI.' }}
            </p>
        </div>

        <div class="flex items-center gap-3">
            <a href="{{ route('demo') }}" class="px-4 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-xs shadow-lg shadow-purple-600/30 transition flex items-center gap-2">
                <span class="w-2 h-2 rounded-full bg-emerald-400 animate-ping"></span>
                <span>{{ $isRtl ? 'اختبار موظف الاستقبال الآلي ←' : 'Test Live WhatsApp Receptionist →' }}</span>
            </a>
        </div>
    </div>

    <!-- 4 Priority B2B Sales KPI Metric Cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <!-- Card 1: Bookings generated by AI -->
        <div class="bg-gradient-to-br from-purple-900 to-indigo-950 text-white rounded-2xl p-5 border border-purple-800/60 shadow-lg relative overflow-hidden group">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-purple-200 uppercase tracking-wider">
                    {{ $isRtl ? 'الحجوزات المحققة بالذكاء الاصطناعي' : 'Bookings Generated by AI' }}
                </span>
                <div class="w-9 h-9 rounded-xl bg-purple-800/80 text-purple-200 flex items-center justify-center font-bold">
                    ⚡
                </div>
            </div>
            <div class="mt-4 flex items-baseline justify-between">
                <div class="text-4xl font-black text-white font-mono">{{ $aiBookingsCount }}</div>
                <span class="text-xs font-bold text-emerald-300 bg-emerald-950/80 px-2 py-0.5 rounded border border-emerald-500/40 font-mono">
                    {{ $isRtl ? '+920 درهم مبيعات' : '+AED 920 Sales' }}
                </span>
            </div>
            <div class="text-[11px] text-purple-200/80 mt-2 font-medium">
                {{ $isRtl ? 'حجوزات آلية عبر استقبال الواتساب' : 'Auto-booked via WhatsApp receptionist' }}
            </div>
        </div>

        <!-- Card 2: New Leads -->
        <div class="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-sm relative overflow-hidden group hover:shadow-md transition">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-slate-500 uppercase tracking-wider">
                    {{ $isRtl ? 'عملاء محتملون جدد' : 'New Leads Captured' }}
                </span>
                <div class="w-9 h-9 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold">
                    🎯
                </div>
            </div>
            <div class="mt-4 flex items-baseline justify-between">
                <div class="text-3xl font-extrabold text-slate-900 font-mono">{{ $leadsCount }}</div>
                <span class="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                    {{ $isRtl ? '100% نسبة التواصل' : '100% Contact Rate' }}
                </span>
            </div>
            <div class="text-[11px] text-slate-400 mt-2">
                {{ $isRtl ? 'تم حفظ بياناتهم آلياً في النظام' : 'Saved automatically to database' }}
            </div>
        </div>

        <!-- Card 3: AI Conversations -->
        <div class="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-sm relative overflow-hidden group hover:shadow-md transition">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-slate-500 uppercase tracking-wider">
                    {{ $isRtl ? 'محادثات الذكاء الاصطناعي' : 'AI Conversations' }}
                </span>
                <div class="w-9 h-9 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center font-bold">
                    🤖
                </div>
            </div>
            <div class="mt-4 flex items-baseline justify-between">
                <div class="text-3xl font-extrabold text-slate-900 font-mono">{{ $conversationsCount }}</div>
                <span class="text-xs font-bold text-purple-600 bg-purple-50 px-2 py-0.5 rounded border border-purple-200">
                    {{ $isRtl ? 'تغطية 24/7' : '24/7 Coverage' }}
                </span>
            </div>
            <div class="text-[11px] text-slate-400 mt-2">
                {{ $isRtl ? 'بدون تفويت أي رسالة عميل' : 'Zero missed customer messages' }}
            </div>
        </div>

        <!-- Card 4: Appointments Today -->
        <div class="bg-white rounded-2xl p-5 border border-slate-200/80 shadow-sm relative overflow-hidden group hover:shadow-md transition">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-slate-500 uppercase tracking-wider">
                    {{ $isRtl ? 'مواعيد اليوم' : 'Appointments Today' }}
                </span>
                <div class="w-9 h-9 rounded-xl bg-slate-100 text-slate-700 flex items-center justify-center font-bold">
                    📅
                </div>
            </div>
            <div class="mt-4 flex items-baseline justify-between">
                <div class="text-3xl font-extrabold text-slate-900 font-mono">{{ $totalAppointmentsCount }}</div>
                <span class="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                    {{ $isRtl ? 'جدول مكتمل' : 'Full Roster' }}
                </span>
            </div>
            <div class="text-[11px] text-slate-400 mt-2">
                {{ $isRtl ? 'موزعة على 4 حلاقين' : 'Scheduled across 4 barbers' }}
            </div>
        </div>
    </div>

    <!-- Sales Analytics Visualization & AI Activity Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        <!-- Left 7 Cols: Sales Conversion Funnel Visualization -->
        <div class="lg:col-span-7 bg-white rounded-2xl p-6 border border-slate-200/80 shadow-sm space-y-6 flex flex-col justify-between">
            <div>
                <div class="flex items-center justify-between pb-3 border-b border-slate-100">
                    <div>
                        <h2 class="text-base font-bold text-slate-900">
                            {{ $isRtl ? 'مسار مبيعات وتحويلات الواتساب' : 'WhatsApp Sales & Conversion Funnel' }}
                        </h2>
                        <p class="text-xs text-slate-500">
                            {{ $isRtl ? 'كيف يحول الذكاء الاصطناعي محادثات الواتساب إلى مبيعات مؤكدة.' : 'How AI turns WhatsApp conversations into confirmed revenue.' }}
                        </p>
                    </div>
                    <div class="text-right">
                        <span class="text-xs font-extrabold text-emerald-600 bg-emerald-50 border border-emerald-200 px-3 py-1 rounded-xl inline-block">
                            {{ $isRtl ? 'نسبة التحويل: 52.9%' : 'Conversion Rate: 52.9%' }}
                        </span>
                    </div>
                </div>

                <!-- Visual Step-by-Step Funnel Bars -->
                <div class="mt-6 space-y-4">
                    <!-- Funnel Stage 1: Conversations -->
                    <div class="space-y-1.5">
                        <div class="flex items-center justify-between text-xs font-bold">
                            <span class="text-slate-700 flex items-center gap-2">
                                <span class="w-2.5 h-2.5 rounded-full bg-purple-600"></span>
                                {{ $isRtl ? '48 محادثة واردة تم التعامل معها' : '48 Conversations Handled' }}
                            </span>
                            <span class="text-slate-400 font-mono">100% {{ $isRtl ? 'رسائل واردة' : 'Inbound' }}</span>
                        </div>
                        <div class="w-full bg-slate-100 h-3.5 rounded-full overflow-hidden">
                            <div class="bg-gradient-to-r from-purple-600 to-indigo-600 h-full rounded-full w-full"></div>
                        </div>
                    </div>

                    <!-- Funnel Stage 2: Leads -->
                    <div class="space-y-1.5 {{ $isRtl ? 'pr-4' : 'pl-4' }}">
                        <div class="flex items-center justify-between text-xs font-bold">
                            <span class="text-slate-700 flex items-center gap-2">
                                <span class="w-2.5 h-2.5 rounded-full bg-indigo-500"></span>
                                {{ $isRtl ? '17 عميل محتمل مؤهل' : '17 Qualified Leads Captured' }}
                            </span>
                            <span class="text-slate-400 font-mono">35.4% {{ $isRtl ? 'نسبة الاستجابة' : 'Lead Rate' }}</span>
                        </div>
                        <div class="w-full bg-slate-100 h-3.5 rounded-full overflow-hidden">
                            <div class="bg-gradient-to-r from-indigo-500 to-teal-500 h-full rounded-full w-[35.4%]"></div>
                        </div>
                    </div>

                    <!-- Funnel Stage 3: Bookings -->
                    <div class="space-y-1.5 {{ $isRtl ? 'pr-8' : 'pl-8' }}">
                        <div class="flex items-center justify-between text-xs font-bold">
                            <span class="text-emerald-700 flex items-center gap-2">
                                <span class="w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
                                {{ $isRtl ? '9 مواعيد مؤكدة ومحجوزة' : '9 Confirmed Appointments Booked' }}
                            </span>
                            <span class="text-emerald-600 font-mono font-extrabold">52.9% {{ $isRtl ? 'نسبة التحويل' : 'Conversion' }}</span>
                        </div>
                        <div class="w-full bg-slate-100 h-3.5 rounded-full overflow-hidden">
                            <div class="bg-gradient-to-r from-emerald-500 to-teal-600 h-full rounded-full w-[52.9%]"></div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Value Highlight Banner -->
            <div class="p-4 rounded-xl bg-purple-50 border border-purple-200/80 flex items-center justify-between text-xs">
                <div class="flex items-center gap-2 text-purple-900 font-medium">
                    <span class="text-lg">💡</span>
                    <span>
                        {{ $isRtl ? 'أثر المبيعات المؤكد: أكثر من 1 من كل 2 عميل محتمل يحول مباشرة إلى موعد مدفوع.' : 'Proven Sales Impact: Over 1 out of 2 captured WhatsApp leads convert directly into paid appointments.' }}
                    </span>
                </div>
            </div>
        </div>

        <!-- Right 5 Cols: AI Activity Log -->
        <div class="lg:col-span-5 bg-white rounded-2xl p-6 border border-slate-200/80 shadow-sm space-y-4">
            <div class="flex items-center justify-between pb-3 border-b border-slate-100">
                <h2 class="text-base font-bold text-slate-900">
                    {{ $isRtl ? 'سجل نشاط الذكاء الاصطناعي' : 'AI Activity Log' }}
                </h2>
                <span class="text-[10px] bg-slate-100 text-slate-600 font-bold px-2 py-0.5 rounded-full font-mono">
                    {{ $isRtl ? 'بث مباشر' : 'Live Feed' }}
                </span>
            </div>

            <div class="space-y-3">
                @if($isRtl)
                    <div class="p-3 rounded-xl border transition flex items-start justify-between gap-3 bg-emerald-50/50 border-emerald-200/70">
                        <div class="flex items-start gap-3">
                            <div class="w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 bg-emerald-600 text-white">✓</div>
                            <div>
                                <div class="text-xs font-bold text-slate-900">تم حجز موعد</div>
                                <div class="text-[11px] text-slate-600 mt-0.5">دانيال براون • قص شعر (80 درهم) الساعة 6:00 مساءً</div>
                                <div class="text-[9px] text-slate-400 mt-1 font-mono">منذ دقيقتين</div>
                            </div>
                        </div>
                        <span class="text-[10px] font-bold px-2 py-0.5 rounded font-mono shrink-0 bg-emerald-100 text-emerald-800">+80 درهم</span>
                    </div>

                    <div class="p-3 rounded-xl border transition flex items-start justify-between gap-3 bg-emerald-50/50 border-emerald-200/70">
                        <div class="flex items-start gap-3">
                            <div class="w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 bg-emerald-600 text-white">✓</div>
                            <div>
                                <div class="text-xs font-bold text-slate-900">الإجابة على سؤال الأسعار</div>
                                <div class="text-[11px] text-slate-600 mt-0.5">محمد حسن استفسر عن باقة شعر + لحية</div>
                                <div class="text-[9px] text-slate-400 mt-1 font-mono">منذ 14 دقيقة</div>
                            </div>
                        </div>
                        <span class="text-[10px] font-bold px-2 py-0.5 rounded font-mono shrink-0 bg-emerald-100 text-emerald-800">تم تزويد السعر</span>
                    </div>

                    <div class="p-3 rounded-xl border transition flex items-start justify-between gap-3 bg-emerald-50/50 border-emerald-200/70">
                        <div class="flex items-start gap-3">
                            <div class="w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 bg-emerald-600 text-white">✓</div>
                            <div>
                                <div class="text-xs font-bold text-slate-900">الإجابة على سؤال ساعات العمل</div>
                                <div class="text-[11px] text-slate-600 mt-0.5">تأكيد أوقات فرع دبي مارينا من 10 صباحاً إلى 10 مساءً</div>
                                <div class="text-[9px] text-slate-400 mt-1 font-mono">منذ 35 دقيقة</div>
                            </div>
                        </div>
                        <span class="text-[10px] font-bold px-2 py-0.5 rounded font-mono shrink-0 bg-emerald-100 text-emerald-800">تم إرسال التفاصيل</span>
                    </div>

                    <div class="p-3 rounded-xl border transition flex items-start justify-between gap-3 bg-amber-50/50 border-amber-200/70">
                        <div class="flex items-start gap-3">
                            <div class="w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 bg-amber-500 text-white">⚠</div>
                            <div>
                                <div class="text-xs font-bold text-slate-900">تحويل المحادثة إلى الموظفين</div>
                                <div class="text-[11px] text-slate-600 mt-0.5">سارة أحمد طلبت باقة عريس مخصصة لـ 5 أشخاص</div>
                                <div class="text-[9px] text-slate-400 mt-1 font-mono">منذ ساعة</div>
                            </div>
                        </div>
                        <span class="text-[10px] font-bold px-2 py-0.5 rounded font-mono shrink-0 bg-amber-100 text-amber-800">يتطلب تدخل بشري</span>
                    </div>
                @else
                    @foreach($aiActivityStream as $item)
                        <div class="p-3 rounded-xl border transition flex items-start justify-between gap-3 {{ $item['type'] === 'success' ? 'bg-emerald-50/50 border-emerald-200/70' : 'bg-amber-50/50 border-amber-200/70' }}">
                            <div class="flex items-start gap-3">
                                <div class="w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs shrink-0 mt-0.5 {{ $item['type'] === 'success' ? 'bg-emerald-600 text-white' : 'bg-amber-500 text-white' }}">
                                    {{ $item['icon'] }}
                                </div>
                                <div>
                                    <div class="text-xs font-bold text-slate-900">{{ $item['title'] }}</div>
                                    <div class="text-[11px] text-slate-600 mt-0.5">{{ $item['details'] }}</div>
                                    <div class="text-[9px] text-slate-400 mt-1 font-mono">{{ $item['time'] }}</div>
                                </div>
                            </div>

                            <span class="text-[10px] font-bold px-2 py-0.5 rounded font-mono shrink-0 {{ $item['type'] === 'success' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">
                                {{ $item['badge'] }}
                            </span>
                        </div>
                    @endforeach
                @endif
            </div>
        </div>
    </div>

    <!-- Today's Schedule Table -->
    <div class="bg-white rounded-2xl border border-slate-200/80 shadow-sm overflow-hidden">
        <div class="p-5 border-b border-slate-100 flex items-center justify-between">
            <div>
                <h2 class="text-base font-bold text-slate-900">{{ $isRtl ? 'جدول مواعيد اليوم' : "Today's Salon Schedule" }}</h2>
                <p class="text-xs text-slate-500">Elite Barber Dubai • Dubai Marina Branch</p>
            </div>
            <a href="{{ route('appointments') }}" class="text-xs font-semibold text-purple-600 hover:text-purple-700">
                {{ $isRtl ? 'عرض التقويم الكامل ←' : 'View Full Agenda →' }}
            </a>
        </div>

        <div class="overflow-x-auto">
            <table class="w-full text-left text-xs text-slate-600">
                <thead class="bg-slate-50 text-slate-400 uppercase font-bold text-[10px] tracking-wider border-b border-slate-100">
                    <tr>
                        <th class="px-5 py-3.5">{{ $isRtl ? 'الوقت' : 'Time' }}</th>
                        <th class="px-5 py-3.5">{{ $isRtl ? 'العميل' : 'Customer' }}</th>
                        <th class="px-5 py-3.5">{{ $isRtl ? 'الخدمة' : 'Service' }}</th>
                        <th class="px-5 py-3.5">{{ $isRtl ? 'الحلاق' : 'Staff' }}</th>
                        <th class="px-5 py-3.5">{{ $isRtl ? 'الحالة' : 'Status' }}</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 font-medium">
                    @forelse($todayAppointments as $app)
                        @php
                            $isHighlighted = ($highlight && str_contains($app->time_slot, '6:00'));
                        @endphp
                        <tr class="transition {{ $isHighlighted ? 'bg-emerald-50/90 font-bold border-l-4 border-emerald-500 ring-2 ring-emerald-400/40' : 'hover:bg-slate-50/80' }}">
                            <td class="px-5 py-4 text-slate-900 font-bold font-mono">
                                {{ $app->time_slot }}
                                @if($isHighlighted)
                                    <span class="inline-block ml-1 text-[9px] bg-emerald-600 text-white px-1.5 py-0.2 rounded">NEW</span>
                                @endif
                            </td>
                            <td class="px-5 py-4">
                                <div class="flex items-center gap-2.5">
                                    <img src="{{ $app->customer->avatar_url }}" alt="" class="w-7 h-7 rounded-full object-cover">
                                    <div>
                                        <div class="font-bold text-slate-800">{{ $app->customer->name }}</div>
                                        <div class="text-[10px] text-slate-400 font-mono">{{ $app->customer->phone }}</div>
                                    </div>
                                </div>
                            </td>
                            <td class="px-5 py-4">
                                <span class="px-2.5 py-1 rounded-lg bg-slate-100 text-slate-700 text-xs font-semibold">
                                    {{ $app->service->name }} (AED {{ number_format($app->service->price, 0) }})
                                </span>
                            </td>
                            <td class="px-5 py-4 font-semibold text-slate-800">{{ $app->staff->name }}</td>
                            <td class="px-5 py-4">
                                <span class="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">
                                    <span class="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> {{ $isRtl ? 'مؤكد' : 'Confirmed' }}
                                </span>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="p-8 text-center text-slate-400">No appointments scheduled for today.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
